name: E2E Tests - All Platforms (Single Report)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch: # Allow manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: System Resource Check
      run: |
        echo "Available system resources:"
        free -h
        nproc
        echo "Node.js memory limit will be set to 4GB"
    
    - name: Run All E2E Tests (All Platforms)
      run: npm run test:ci
      env:
        CI: true
        ENV: ci
        BASE_URL: https://opensource-demo.orangehrmlive.com
        ORANGEHRM_BASE_URL: https://opensource-demo.orangehrmlive.com
        ORANGEHRM_USERNAME: Admin
        ORANGEHRM_PASSWORD: admin123
        HEADLESS: true
    
    - name: Post-Test Resource Check
      if: always()
      run: |
        echo "Final system resource usage:"
        free -h
        df -h
        echo "All platform test execution completed"
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-all-platforms-${{ github.run_id }}
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-all-platforms-${{ github.run_id }}
        path: test-results/
        retention-days: 30
    
    - name: Upload traces
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-traces-all-platforms-${{ github.run_id }}
        path: test-results/**/trace.zip
        retention-days: 30

    - name: Comment PR with test results
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          let comment = '## 🎭 E2E Test Results - All Platforms\n\n';
          
          try {
            if (fs.existsSync('playwright-report/index.html')) {
              comment += '✅ All platform tests completed successfully!\n';
              comment += `📊 **Single aggregated report** contains results from all browsers and devices.\n\n`;
              comment += `🔗 **Test Coverage:**\n`;
              comment += `- 🖥️ **Desktop:** Chrome, Firefox, Safari, Edge\n`;
              comment += `- 📱 **Mobile:** Chrome Mobile, Safari Mobile\n`;
              comment += `- 📟 **Tablet:** iPad Pro\n\n`;
              comment += `📈 [View Aggregated Report](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})\n`;
              if (context.payload.pull_request) {
                comment += `- 🎯 **Branch:** ${context.payload.pull_request.head.ref}\n`;
                comment += `- 📝 **Commit:** ${context.payload.pull_request.head.sha.substr(0, 7)}\n`;
              }
            } else {
              comment += '❌ Tests may have failed. Check the action logs for details.\n';
            }
          } catch (error) {
            comment += `⚠️ Could not parse test results: ${error.message}\n`;
          }
          
          if (context.payload.pull_request) {
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }