name: Playwright Tests - Daily Scheduled Run

# This workflow runs automatically once every 24 hours
# It does NOT trigger on commits or pull requests
# Manual execution is available via GitHub Actions UI

on:
  schedule:
    # Run every 24 hours at 2:00 AM UTC
    # Cron format: minute hour day month weekday
    # 0 2 * * * = Daily at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger only

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Optimal sharding for GitHub Actions free plan
        # 4 shards = 4 parallel jobs, each with 1 worker = efficient resource usage
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: System Resource Check
      run: |
        echo "Available system resources:"
        free -h
        nproc
        echo "Node.js memory limit will be set to 4GB"
    
    - name: Run Playwright tests
      run: npm run test:ci-sharded -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      env:
        CI: true
        ENV: ci
        BASE_URL: https://opensource-demo.orangehrmlive.com
        ORANGEHRM_BASE_URL: https://opensource-demo.orangehrmlive.com
        ORANGEHRM_USERNAME: Admin
        ORANGEHRM_PASSWORD: admin123
        HEADLESS: true
    
    - name: Post-Test Resource Check
      if: always()
      run: |
        echo "Final system resource usage:"
        free -h
        df -h
        echo "Test execution completed for shard ${{ matrix.shardIndex }}/${{ matrix.shardTotal }}"
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-shard-${{ matrix.shardIndex }}
        path: playwright-report/
        retention-days: 30
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-shard-${{ matrix.shardIndex }}
        path: test-results/
        retention-days: 30
    
    - name: Upload Traces
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-traces-shard-${{ matrix.shardIndex }}
        path: test-results/**/trace.zip
        retention-days: 30